#ifndef __KARBAZOL_DRAGNDROP_2_0__DNDMSGS_H__
#define __KARBAZOL_DRAGNDROP_2_0__DNDMSGS_H__

// Message ids to communicate
#define WM_DND_TOOLWINDOW_BASE (WM_USER + 1978)
#define WM_PREPAREFORDRAGGING  (WM_DND_TOOLWINDOW_BASE + 1)
//#define WM_GETACTIVEDND (WM_DND_TOOLWINDOW_BASE + 2)
// Returns HOLDER_YES or HOLDER_NOT
#define WM_ISACTIVEDND (WM_DND_TOOLWINDOW_BASE + 3)
#define WM_ISDRAGGIN (WM_DND_TOOLWINDOW_BASE + 4)
#define WM_SHOWDNDWINDOW (WM_DND_TOOLWINDOW_BASE + 5)
#define WM_HIDEDNDWINDOW (WM_DND_TOOLWINDOW_BASE + 6)
#define WM_DND_SHOWPOPUPMENU (WM_DND_TOOLWINDOW_BASE + 7)

#endif // __KARBAZOL_DRAGNDROP_2_0__DNDMSGS_H__

